import solc from 'solc'; import fs from 'node:fs'; import path from 'node:path';
const root = new URL('../../../contracts', import.meta.url).pathname;
const remap = [['@openzeppelin/contracts/', 'lib/openzeppelin-contracts/contracts/'], ['forge-std/', 'lib/forge-std/src/']];
const names = ['CordonVault','OracleRouter','MarketSession','SettlementOracle','SpurVault','GraftVault','HarvestAuction'];
const sources = {};
for (const n of names) sources['src/'+n+'.sol'] = { content: fs.readFileSync(path.join(root,'src',n+'.sol'),'utf8') };
function findImports(p){ let q=p; for(const [a,b] of remap) if(p.startsWith(a)) q=b+p.slice(a.length);
  const f=path.join(root,q); if(fs.existsSync(f)) return {contents:fs.readFileSync(f,'utf8')}; return {error:'nf '+p}; }
const input={language:'Solidity',sources,settings:{evmVersion:'cancun',optimizer:{enabled:true,runs:200},outputSelection:{'*':{'*':['abi']}}}};
const out=JSON.parse(solc.compile(JSON.stringify(input),{import:p=>{
  // resolve relative imports inside src
  let r=findImports(p); if(r.error && fs.existsSync(path.join(root,p))) r={contents:fs.readFileSync(path.join(root,p),'utf8')}; return r;}}));
if(out.errors) for(const e of out.errors) if(e.severity==='error') console.log(e.formattedMessage);
const OUT=[];
for(const n of names){ const abi=out.contracts['src/'+n+'.sol'][n].abi; OUT.push('\nexport const '+n[0].toLowerCase()+n.slice(1)+'Abi = '+JSON.stringify(abi,null,2)+' as const;\n'); }
fs.writeFileSync(new URL('../src/abis.ts', import.meta.url).pathname, '// GENERATED by scripts/gen-abis.mjs from contracts/src (solc 0.8.28). Jangan diedit tangan.\n'+OUT.join(''));
